### ISSUE TITLE
NoMethodError: undefined method `tell' for nil

### ISSUE THREAD

**Issue by niktexnik** [ip2location/ip2location-ruby#7]
Hello, after update rails(Rails 7.1.3.2) and ruby 3.3.0
when I write command Ip2location.new.open(Rails.root.join("db/IP2LOCATION-LITE-DB1.BIN")).get_all('8.8.8.8')
get_country_short and e.t.c
return next error
NoMethodError: undefined method `tell' for nil
from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.0.3/lib/ip2location_ruby/i2l_string_data.rb:8:in `read_and_return_value'

**Comment by niktexnik** [comment]
I tried different versions, last version was tried too, but error present  again

**Comment by ip2location-com** [comment]
Hi @niktexnik, we are sorry that this library does not support Rails.

**Comment by niktexnik** [comment]
When I have ruby 2.4.1 it's working, it's crashed after update ruby to 3.3.0....
But it's the same thing, it's the Ruby framework.
Ok, when I use Ruby, I have same problem.
irb(main):002> Ip2location.new.open("~/IP2LOCATION-LITE-DB1.BIN").get_all('8.8.8.8')
/home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.0.3/lib/ip2location_ruby/i2l_string_data.rb:8:in `read_and_return_value': undefined method `tell' for nil (NoMethodError)

    old_offset = file.tell
                     ^^^^^
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base_primitive.rb:124:in `do_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/struct.rb:141:in `block in do_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/struct.rb:141:in `each'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/struct.rb:141:in `do_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:149:in `block in read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:243:in `start_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:147:in `read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:21:in `read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.0.3/lib/ip2location_ruby.rb:167:in `bsearch'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.0.3/lib/ip2location_ruby.rb:53:in `get_all'
        from (irb):2:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /home/niktexnik/.gem/ruby/3.3.0/gems/irb-1.12.0/exe/irb:9:in `<top (required)>'
        from /home/niktexnik/.rbenv/versions/3.3.0/bin/irb:25:in `load'
        from /home/niktexnik/.rbenv/versions/3.3.0/bin/irb:25:in `<main>'
![image](https://github.com/ip2location/ip2location-ruby/assets/74414806/32ef3989-d99e-4d69-b638-1bb5d6c26677)

**Comment by niktexnik** [comment]
![image](https://github.com/ip2location/ip2location-ruby/assets/74414806/4d89aae0-45ac-4de2-bd61-6d9829ccbd1c)
when I open file, all OK

![image](https://github.com/ip2location/ip2location-ruby/assets/74414806/982b71cf-7528-49cf-a732-5fa08916ae2d)
after use different methods, error

**Comment by ip2location-com** [comment]
We noticed you are using the older version of the library. Kindly update the library to the latest version and try again. You can use the command `gem update ip2location_ruby` to update the library.

**Comment by niktexnik** [comment]
I tried different versions, example(using last version your gem)

irb(main):001> require 'ip2location_ruby'
=> true
irb(main):002> z = Ip2location.new.open("~/IP2LOCATION-LITE-DB1.BIN")
=>
#<Ip2location:0x00007f45997715b0
...
irb(main):003> z.get_country_short('8.8.8.8')
/home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.7.2/lib/ip2location_ruby/i2l_string_data.rb:8:in `read_and_return_value': undefined method `tell' for nil (NoMethodError)

    old_offset = file.tell
                     ^^^^^
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base_primitive.rb:124:in `do_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/struct.rb:141:in `block in do_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/struct.rb:141:in `each'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/struct.rb:141:in `do_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:149:in `block in read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:243:in `start_read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:147:in `read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bindata-2.5.0/lib/bindata/base.rb:21:in `read'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.7.2/lib/ip2location_ruby.rb:690:in `bsearch'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.7.2/lib/ip2location_ruby.rb:112:in `get_record'
        from /home/niktexnik/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ip2location_ruby-8.7.2/lib/ip2location_ruby.rb:260:in `get_country_short'
        from (irb):3:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /home/niktexnik/.gem/ruby/3.3.0/gems/irb-1.12.0/exe/irb:9:in `<top (required)>'
        from /home/niktexnik/.rbenv/versions/3.3.0/bin/irb:25:in `load'
        from /home/niktexnik/.rbenv/versions/3.3.0/bin/irb:25:in `<main>'
irb(main):004>

**Comment by ip2location-com** [comment]
We have fixed the error. Kindly update the library to the latest version and try again.

**Comment by niktexnik** [comment]
it's work! Thanks!
